### 1.Model
model:
  name: "Whole_model_light256_V2"
  backbone: "without-pretrain"
  height: 720
  width: 960
  classes: 11
#  augmentation_train: get_training_augmentation(height, width)
#  augmentation_valid: get_validation_augmentation(height, width)
### 2.Optimizer
optimizer:
  init_lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001

### 3.Trainning 
train:
  specific_gpu_num: "0"     # for example: "0", "1" or "0, 1"
  train_batch_size: 4
  # adjust according to gpu resources
  valid_batch_size: 1
  train_dir: "./datasets/CamVid/camvid_train.txt"
  val_dir: "./datasets/CamVid/camvid_val.txt"
  test_dir: "./datasets/CamVid/camvid_test.txt"
  epochs: 1000
  log_iter: 10        # print log every log-iter 
  val_epoch: 1        # run validation every val-epoch
  log_save_dir: "./results/camvid_log"  #日志保存在这里
  ckpt_dir: "./results/camvid_ckpt/" # ckpt and trainning log will be saved here

### 4.Test
test:
  ckpt_path: "./results/camvid_ckpt/Camvid_256_0.749_best_model.pth" # set the pretrained model path correctly